name: minecraft_services_client
description: "An API client for the Minecraft Services API"
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.9.0
resolution: workspace

dependencies:
  meta: ^1.16.0
  json_utils: ^1.0.0
  result: ^1.0.0
  api_client: ^1.0.0

dev_dependencies:
  test: ^1.24.0
