name: api_client
description: "Enforces explicit failure handling for API calls."
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.9.0
resolution: workspace

dependencies:
  result: ^1.0.0
  json_utils: ^1.0.0
  http: ^1.4.0
  meta: ^1.16.0

dev_dependencies:
  test: ^1.24.0
  mocktail: ^1.0.4
