import 'package:api_client/src/multipart/multipart_body.dart';
import 'package:json_utils/json_utils.dart';
import 'package:meta/meta.dart';

/// Represents the body of an HTTP request.
@immutable
sealed class RequestBody {
  const RequestBody();

  /// A JSON body that will be automatically encoded to a [String]
  /// with the `Content-Type: application/json` header.
  const factory RequestBody.json(JsonMap json) = JsonRequestBody;

  /// A multipart/form-data body,
  /// the `Content-Type: multipart/form-data; boundary=$boundary` header is set automatically,
  /// with the boundary value generated by the underlying HTTP client.
  const factory RequestBody.multipart(MultipartBody multipart) =
      MultipartRequestBody;

  /// A raw body passed through to the HTTP client as-is.
  /// Use this for custom cases (e.g., plain text, or already-encoded JSON).
  const factory RequestBody.raw(Object raw) = RawRequestBody;

  JsonMap? get jsonOrNull => (this as JsonRequestBody?)?.json;

  MultipartBody? get multipartOrNull =>
      (this as MultipartRequestBody?)?.multipart;

  Object? get rawOrNull => (this as RawRequestBody?)?.raw;
}

final class JsonRequestBody extends RequestBody {
  const JsonRequestBody(this.json);
  final JsonMap json;
}

final class MultipartRequestBody extends RequestBody {
  const MultipartRequestBody(this.multipart);
  final MultipartBody multipart;
}

final class RawRequestBody extends RequestBody {
  const RawRequestBody(this.raw);
  final Object raw;
}
