name: json_utils
description: "Safe JSON decoding & deserialization and pretty encoding"
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.9.0
resolution: workspace

dependencies:
  result: ^1.0.0

dev_dependencies:
  test: ^1.24.0
