import 'package:http/http.dart' as http show MultipartFile;
import 'package:json_utils/json_utils.dart';
import 'package:result/result.dart';
import 'package:safe_http/src/api_client/api_failures.dart';
import 'package:safe_http/src/api_client/http_response.dart';
import 'package:safe_http/src/multipart/multipart_body.dart' show MultipartBody;

/// An HTTP client for APIs that return responses using the [Result] pattern.
///
/// Provides the following on top of a standard HTTP client:
///
/// * Wraps all responses in a [Result], enforce handling transport-level issues.
///
/// * When using [requestJson], automatically adds the `Accept: application/json` header,
///   and expects responses to be JSON.
///
/// * For all requests except [HttpMethod.get]:
///   Optionally encodes the request body as JSON and sets the
///   `Content-Type: application/json` header when sending a JSON body,
///   by passing `true` to [isJsonBody] argument when calling either [request]
///   or [requestJson].
///
/// * When using [HttpMethod.post], [HttpMethod.put], or [HttpMethod.patch]:
///   Supports a multipart request body and sets the
///   `Content-Type: multipart/form-data; boundary=$boundary` header,
///   with the boundary automatically generated by the HTTP client implementation,
///   by passing a [MultipartBody] to [body] argument when calling either [request]
///   or [requestJson].
///
/// Example:
///
/// ```dart
/// final ApiClient apiClient = ...;
///
/// final result = await apiClient.requestJson<Example, String>(
///   Uri.https('api.example.com'),
///   method: HttpMethod.get,
///   deserializeSuccess: (response) => Example.fromJson(response.body),
///   deserializeFailure: (response) => response.body['error_code']! as String,
/// );
/// ```
///
/// This client interface applies specific design decisions:
///
/// * Applies only to [requestJson]:
///   Requires JSON format for all successful and error responses.
///   If the API does not always return JSON, use [request]
///   instead for more control.
///
/// * The class [http.MultipartFile] from `package:http` is part of this API for
///   performance, simplicity, testability, and separation of concerns reasons.
///
///   This makes replacing the `package:http` dependency slightly harder.
///   For more info, visit the file that exports [http.MultipartFile] which is
///   the same file that defines [MultipartBody].
abstract interface class ApiClient {
  /// Sends an HTTP request and deserializes the JSON response.
  ///
  /// Unlike [request], this automatically adds the `Accept: application/json` header
  /// and expects all responses to be valid JSON.
  ///
  /// If the API returns inconsistent responses (e.g., sometimes JSON, sometimes empty or non-JSON),
  /// use [request] instead for more control.
  ///
  /// Use [deserializeSuccess] and [deserializeFailure] to parse the response body.
  /// Both receive the [HttpResponse] with the decoded JSON as a [JsonMap],
  /// suitable for passing to `fromJson`.
  ///
  /// - [deserializeSuccess] is used for 2xx responses.
  /// - [deserializeFailure] is used for non-2xx responses (e.g., 4xx, 5xx).
  ///
  /// {@macro request}
  JsonApiResultFuture<S, F> requestJson<S, F>(
    Uri url, {
    required HttpMethod method,
    Map<String, String>? headers,
    Object? body,
    bool isJsonBody = false,
    required JsonResponseDeserializer<S> deserializeSuccess,
    required JsonResponseDeserializer<F> deserializeFailure,
  });

  /// Sends an HTTP request.
  ///
  /// {@template request}
  ///
  /// Throws an [ArgumentError] if [method] is [HttpMethod.get] and [body] is non-null,
  /// since GET requests must not have a body.
  /// The [isJsonBody] argument is silently ignored when [body] is null.
  ///
  /// When [isJsonBody] is `true`, [body] must be a [JsonMap] and will be
  /// automatically JSON-encoded. In this case, the `Content-Type: application/json`
  /// header is added.
  ///
  /// Throws an [ArgumentError] if [isJsonBody] is `true` but [body] is not a [JsonMap].
  ///
  /// If [body] is a [MultipartBody], the request is sent as multipart/form-data,
  /// the `Content-Type: multipart/form-data; boundary=$boundary` header is set automatically,
  /// with the boundary value generated by the underlying HTTP client.
  ///
  /// The [isJsonBody] argument must be `false` when using a [MultipartBody],
  /// otherwise an [ArgumentError] is thrown.
  ///
  /// If [isJsonBody] is `false` and [body] is not [MultipartBody],
  /// [body] is passed as-is to the HTTP client.
  ///
  /// {@endtemplate}
  StringApiResultFuture request(
    Uri url, {
    required HttpMethod method,
    Map<String, String>? headers,
    Object? body,
    bool isJsonBody = false,
  });
}

enum HttpMethod { get, post }

typedef JsonResponseDeserializer<T> = T Function(JsonHttpResponse response);

// S and F are usually parsed from the JSON response, but they can be anything.
// S represents the success response.
// F represents the error response.
typedef JsonApiResult<S, F> = Result<HttpResponse<S>, ApiFailure<F>>;
typedef JsonApiResultFuture<S, F> = Future<JsonApiResult<S, F>>;

typedef StringApiResult = Result<StringHttpResponse, GeneralApiFailure<String>>;
typedef StringApiResultFuture = Future<StringApiResult>;
