name: file_executable
description: "Native chmod support to make files executable on Linux and macOS."
version: 1.0.0

environment:
  sdk: ^3.9.0
resolution: workspace

dependencies:
  ffi: ^2.1.0

dev_dependencies:
  test: ^1.24.0
