name: file_executable
description: "Native chmod support to make files executable on Linux and macOS."
version: 1.0.0

environment:
  sdk: ^3.9.0

dependencies:
  ffi: ^2.1.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
