name: safe_http
description: "Enforces explicit failure handling for HTTP calls."
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.8.1

dependencies:
  result:
    path: ../result
  json_utils:
    path: ../json_utils
  http: ^1.4.0
  meta: ^1.16.0

dev_dependencies:
  test: ^1.24.0
  mocktail: ^1.0.4
